# format: windowrule=Parameter:Values,appid:Values,title:Values
# note: mango uses appid instead of hyprland's class

# tag assignment (hypr: workspace; tag 2 pinned to HDMI-A-1 like hypr's workspace=2 monitor:HDMI-A-1)
windowrule=tags:1,monitor:HDMI-A-1,appid:^code
windowrule=tags:2,monitor:HDMI-A-1,appid:^firefox
windowrule=tags:3,isopensilent:1,title:Discord
windowrule=tags:3,isopensilent:1,appid:^spotify
windowrule=tags:3,isopensilent:1,appid:^(obsidian)$
windowrule=tags:4,isopensilent:1,appid:^(steam)$
windowrule=tags:4,isopensilent:1,title:^OBS


# opacity override
windowrule=focused_opacity:1,unfocused_opacity:1,appid:^Min$
windowrule=focused_opacity:1,unfocused_opacity:1,appid:scrcpy
windowrule=focused_opacity:1,appid:^(firefox|ueberzug|Insomnia|chrome)(.*)

# floating size for save dialogs
windowrule=width:800,height:600,isfloating:1,title:^(Save|File Upload)

windowrule=noblur,floating:1
