#!/bin/bash

check_battery() {
  BAT_TR=15
  STATUS=$(acpi -b | awk '{print $3}' | tr -d ',')
  PERCENTAGE=$(acpi -b | awk '{print $4}' | tr -d '%,')

  if [ $STATUS == "Charging" ]; then
    dunstctl close
    return 0
  fi

  if [ $STATUS == "Discharging" ] && [ $PERCENTAGE -lt $BAT_TR ]; then
    notify-send -u critical "Battery low!" "Plug in your charger" -i $HOME/.config/dunst/icons/battery-warning-vertical.svg
  fi
}

while true; do
  check_battery
  sleep 60
done
