#!/bin/bash

menu="[lock]\n[suspend]\n[reboot]\n[poweroff]"

choice=$(printf "$menu" | rofi -dmenu -i -theme "$HOME/.config/rofi/themes/powermenu.rasi" -p " ")

case "$choice" in
\[lock\]) loginctl lock-session ;;
\[suspend\]) systemctl suspend ;;
\[rebbot\]) systemctl reboot ;;
\[poweroff\]) systemctl poweroff ;;
*) exit 0 ;;
esac
