#!/bin/bash

# get the current volume
volume=$(pactl list sinks | grep -m 1 'Volume: front-left:' | awk '{print $5}' | sed 's/%//g')

echo $volume
if [ "$1" = "up" ] && [ "$volume" -lt 100 ]; then
	pactl set-sink-volume @DEFAULT_SINK@ +2%
elif [ "$1" = "down" ]; then
	pactl set-sink-volume @DEFAULT_SINK@ -2%
elif [ "$1" = "mute" ]; then
	pactl set-sink-mute @DEFAULT_SINK@ toggle
fi
