#!/bin/bash

jq_del='del(.[] | select(.["description"] == "Loopback Analog Stereo"))'
jq_get_vol='.[].volume.["front-left"].["value_percent"]'

volume=$(pactl -f json list sinks | jq "$jq_del" | jq "$jq_get_vol" | sed 's/["%]//g')

if [ "$1" = "up" ] && [ "$volume" -lt 100 ]; then
  pactl set-sink-volume @DEFAULT_SINK@ +2%
elif [ "$1" = "down" ]; then
  pactl set-sink-volume @DEFAULT_SINK@ -2%
elif [ "$1" = "mute" ]; then
  pactl set-sink-mute @DEFAULT_SINK@ toggle
fi
