#!/bin/bash

wallsDir="$HOME/Pictures/walls"
currentWall="$HOME/.current-wall"
wall=$(for file in "$wallsDir"/*; do
  [ -f "$file" ] && echo -e "$(basename "$file")\0icon\x1f$file"
done | rofi -dmenu -i -p "Wallpaper" -theme "$HOME/.config/rofi/themes/wall-changer.rasi")

if [ -n "$wall" ]; then
  awww img --transition-type wipe --transition-angle 50 "$wallsDir/$wall"

  if [ "$wallsDir/$wall" = $(cat $currentWall) ]; then
    notify-send -u normal "wall-changer" "$wall is already set as wallpaper" -i "$wallsDir/$wall"
    exit 0
  fi

  notify-send -u normal "wall-changer" "Wallpaper changed to $wall" -i "$wallsDir/$wall"
  echo "$wallsDir/$wall" >$currentWall
fi
