#!/bin/bash

wallsDir="$HOME/Pictures/walls"
currentWall="$HOME/.current-wall"
wall=$(ls $wallsDir | rofi -dmenu -i -p "Wallpaper" -theme-str 'element-icon { enabled: false; }')

if [ -n "$wall" ]; then
  swww img --transition-type wipe --transition-angle 50 "$wallsDir/$wall"

  if [ "$wallsDir/$wall" = $(cat $currentWall) ]; then
    notify-send -u normal "wall-changer" "$wall is already set as wallpaper" -i "$wallsDir/$wall"
    exit 0
  fi

  notify-send -u normal "wall-changer" "Wallpaper changed to $wall" -i "$wallsDir/$wall"
  echo "$wallsDir/$wall" >$currentWall
fi
